"""Pre-built scenario templates for the Digital Twin simulation engine."""

SCENARIO_TEMPLATES = [
    {
        "name": "Strait of Hormuz Partial Closure",
        "description": "Partial blockade of the Strait of Hormuz — 50% reduction in tanker traffic for 30 days. Primary impact on Middle East crude exports to Asia.",
        "category": "chokepoint",
        "severity": "high",
        "is_template": True,
        "config": {
            "duration_days": 30,
            "severity": 0.5,
            "affected_chokepoint": "strait_of_hormuz",
            "affected_routes": ["middle_east_to_asia"],
            "transit_delay_hours": 48,
            "insurance_multiplier": 3.0,
        },
        "assumptions": {
            "middle_east_supply_cut_pct": 0.5,
            "spare_capacity_available": True,
            "alternative_routes_available": True,
            "spr_release_authorized": True,
            "demand_reduction_pct": 0.05,
        },
    },
    {
        "name": "Strait of Hormuz Full Closure",
        "description": "Complete blockade of the Strait of Hormuz — 100% of tanker traffic halted for 60 days. Worst-case scenario for Middle East crude exports.",
        "category": "chokepoint",
        "severity": "critical",
        "is_template": True,
        "config": {
            "duration_days": 60,
            "severity": 1.0,
            "affected_chokepoint": "strait_of_hormuz",
            "affected_routes": [
                "middle_east_to_asia", "middle_east_to_europe",
                "middle_east_to_africa",
            ],
            "transit_delay_hours": 999,
            "insurance_multiplier": 10.0,
        },
        "assumptions": {
            "middle_east_supply_cut_pct": 1.0,
            "spare_capacity_available": False,
            "alternative_routes_available": False,
            "spr_release_authorized": True,
            "emergency_demand_reduction_pct": 0.15,
        },
    },
    {
        "name": "Red Sea Shipping Disruption",
        "description": "Red Sea shipping disrupted due to military activity — 70% of Suez Canal traffic rerouted around Cape of Good Hope for 45 days.",
        "category": "conflict",
        "severity": "high",
        "is_template": True,
        "config": {
            "duration_days": 45,
            "severity": 0.7,
            "affected_region": "red_sea",
            "affected_routes": ["suez_canal_transit"],
            "transit_delay_hours": 240,
            "insurance_multiplier": 5.0,
        },
        "assumptions": {
            "suez_traffic_reduction_pct": 0.7,
            "cape_route_delay_days": 10,
            "freight_cost_increase_pct": 0.5,
            "spare_capacity_available": False,
            "alternative_suppliers_available": True,
        },
    },
    {
        "name": "Russian Export Ban",
        "description": "Complete embargo on Russian crude and refined product exports — 100% of Russian energy exports halted for 90 days.",
        "category": "sanctions",
        "severity": "critical",
        "is_template": True,
        "config": {
            "duration_days": 90,
            "severity": 1.0,
            "sanctioned_countries": ["Russia"],
            "sanctioned_commodities": ["crude", "refined_products", "lng"],
            "affected_suppliers": ["russian_suppliers"],
        },
        "assumptions": {
            "russian_export_loss_pct": 1.0,
            "global_oil_price_increase_pct": 0.25,
            "alternative_suppliers_available": True,
            "spare_opec_capacity_available": True,
            "lng_substitution_possible": True,
        },
    },
    {
        "name": "OPEC Coordinated Production Cut",
        "description": "OPEC+ agrees to coordinated production cut of 3 million barrels per day for 6 months.",
        "category": "supply_shock",
        "severity": "high",
        "is_template": True,
        "config": {
            "duration_days": 180,
            "severity": 0.6,
            "production_cut_bpd": 3000000,
            "affected_regions": ["middle_east", "africa"],
        },
        "assumptions": {
            "global_supply_reduction_bpd": 3000000,
            "price_increase_pct": 0.20,
            "non_opec_production_increase_bpd": 500000,
            "spr_release_authorized": True,
        },
    },
    {
        "name": "Gujarat Cyclone",
        "description": "Category 4 cyclone making landfall on Gujarat coast — major refineries offline, ports closed for 2 weeks.",
        "category": "natural_disaster",
        "severity": "high",
        "is_template": True,
        "config": {
            "duration_days": 21,
            "severity": 0.7,
            "cyclone_category": 4,
            "affected_ports": ["jamnagar", "kandla", "mundra"],
            "affected_refineries": ["jamnagar", "mangalore_rel", "kochi"],
            "port_closure_days": 14,
            "refinery_offline_days": 21,
        },
        "assumptions": {
            "gujarat_port_closure_pct": 1.0,
            "gujarat_refinery_downtime_pct": 1.0,
            "other_indian_ports_can_absorb_pct": 0.3,
            "inventory_can_bridge_pct": 0.5,
        },
    },
    {
        "name": "Refinery Fire — Jamnagar",
        "description": "Major fire at Reliance's Jamnagar refinery — world's largest refining complex — forces 45-day shutdown of one unit.",
        "category": "infrastructure_failure",
        "severity": "high",
        "is_template": True,
        "config": {
            "duration_days": 45,
            "severity": 0.6,
            "affected_refinery": "jamnagar",
            "capacity_lost_bpd": 350000,
            "unit_type": "crude_distillation_unit",
        },
        "assumptions": {
            "jamnagar_capacity_loss_pct": 0.3,
            "other_refineries_can_increase_pct": 0.4,
            "product_imports_possible": True,
            "spr_release_authorized": False,
        },
    },
    {
        "name": "Combined Crisis — Hormuz + Red Sea",
        "description": "Simultaneous Hormuz closure and Red Sea disruption — worst-case combined scenario. Both chokepoints blocked simultaneously.",
        "category": "custom",
        "severity": "critical",
        "is_template": True,
        "config": {
            "duration_days": 45,
            "severity": 1.0,
            "combined_events": True,
            "events": [
                {
                    "type": "chokepoint_blockade",
                    "name": "strait_of_hormuz",
                    "severity": 0.8,
                    "delay_days": 60,
                },
                {
                    "type": "chokepoint_blockade",
                    "name": "red_sea",
                    "severity": 0.6,
                    "delay_days": 45,
                },
            ],
        },
        "assumptions": {
            "middle_east_supply_cut_pct": 0.9,
            "suez_traffic_reduction_pct": 0.7,
            "spare_capacity_available": False,
            "alternative_routes_available": False,
            "spr_release_authorized": True,
            "emergency_demand_reduction_pct": 0.25,
            "global_recession_risk_pct": 0.6,
        },
    },
    {
        "name": "India Supply Chain Stress Test",
        "description": "Comprehensive stress test — 30% reduction in all import corridors for 90 days. Tests the resilience of India's energy supply chain under sustained pressure.",
        "category": "supply_shock",
        "severity": "high",
        "is_template": True,
        "config": {
            "duration_days": 90,
            "severity": 0.6,
            "import_reduction_pct": 0.3,
            "india_specific": True,
            "affected_corridors": ["all_india_imports"],
        },
        "assumptions": {
            "india_import_reduction_pct": 0.3,
            "spr_release_authorized": True,
            "domestic_production_increase_pct": 0.1,
            "demand_reduction_pct": 0.1,
            "alternative_suppliers_found_pct": 0.2,
        },
    },
    {
        "name": "Power Grid Failure",
        "description": "Major power grid failure affecting Western India — refineries and ports in Gujarat/Maharashtra lose grid power for 7 days.",
        "category": "infrastructure_failure",
        "severity": "elevated",
        "is_template": True,
        "config": {
            "duration_days": 14,
            "severity": 0.5,
            "affected_region": "western_india",
            "affected_refineries": ["jamnagar", "mumbai", "mangalore"],
            "affected_ports": ["jamnagar", "mumbai", "kandla"],
        },
        "assumptions": {
            "grid_outage_days": 7,
            "backup_power_available_pct": 0.4,
            "refinery_reduced_throughput_pct": 0.6,
            "port_congestion_increase_pct": 0.3,
        },
    },
]
